# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-06 13:11
from __future__ import unicode_literals

import adminsortable.fields
import carousel.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('principal', 'Principal (1350px x 563px)')], max_length=50, verbose_name='Carousel')),
                ('published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'carousel',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to=carousel.models.Photo.get_upload_to_image, verbose_name='Imagem')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Título')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição')),
                ('link', models.CharField(blank=True, max_length=100, null=True, verbose_name='Link')),
                ('carousel', adminsortable.fields.SortableForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carousel.Carousel')),
            ],
            options={
                'verbose_name': 'imagem',
                'verbose_name_plural': 'imagens',
            },
        ),
    ]
