# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-06 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'ordering': ['carousel_order'], 'verbose_name': 'carousel'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['photo_order'], 'verbose_name': 'imagem', 'verbose_name_plural': 'imagens'},
        ),
        migrations.AddField(
            model_name='carousel',
            name='carousel_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
