# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-06 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0002_auto_20171006_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='type',
            field=models.CharField(choices=[('principal', 'Principal (1280px x 377px)')], max_length=50, verbose_name='Carousel'),
        ),
    ]
